site_name: dslogos
site_description: Test Assignment
repo_url: https://github.com/denchip/dslogos_assignment
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/denchip">denchip</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
